package com.eventfinder.www.eventfindermobile;

/**
 * Created by redre on 4/27/2018.
 */

public class InterestArray {
    CharSequence[] ints = new CharSequence[] {
    "Acting", "Badmitton", "Band", "Baseball",
    "Basketball",
    "Bird Watching",
    "Billiards",
    "Board Games",
    "Boating",
    "Bowling",
    "Boxing",
    "Camping",
    "Chess",
    "Color Guard",
    "Cooking",
    "Dancing",
    "Darts",
    "Debate",
    "Drawing",
    "Fencing",
    "Fishing",
    "Football",
    "Gardening",
    "Ghost Hunting",
    "Golf",
    "Gymnastics",
    "Hiking",
    "Hockey",
    "Horseback Riding",
    "Hunting",
    "Ice Skating",
    "Kayaking",
    "Knitting",
    "LARPing",
    "Laser Tag",
    "Martial Arts",
    "Mountain Biking",
    "Orchestra",
    "Paintballing",
    "Painting",
    "Parkour",
    "Photography",
    "Poker",
    "Powerlifting",
    "Pottery",
    "Programming",
    "Rafting",
    "Rappelling",
    "Reading",
    "Rock Climbing",
    "Roller Skating",
    "Running",
    "Scuba Diving",
    "Sewing",
    "Shooting",
    "Shopping",
    "Singing",
    "Skateboarding",
    "Skiing",
    "Skydiving",
    "Snowboarding",
    "Soccer",
    "Surfing",
    "Swimming",
    "Traveling",
    "Video Games",
    "Volleyball",
    "Watching Movies",
    "Wood Carving",
    "Wrestling",
    "Writing",
    "Yoga"};
}
